### ISSUE TITLE
no flag --bootstrap_number in caweat.py ?

### ISSUE THREAD

**Issue by albarron** [cristinae/CA-WEAT#2]
https://github.com/cristinae/CA-WEAT/blob/41b647fe38024951c4b2e98881195c2b283f3d62/runCaweat.sh#L9

Apparently, the flag, included in the sh, is not available in the caweat.py file? This happened when trying to run caweat.py directly, copying from the call in runCaweat.sh

**Comment by albarron** [comment]
@cristinae I do not see this flag in caweat.py. Where is the problem: the flag has been deprecated or the up-to-date version is missing?

**Comment by iamshnoo** [comment]
Hello, I came across this paper for a class project. And wanted to understand how you are approaching bootstrapping here. Is this issue resolved? Do you have an updated version of the caweat.py file where I can pass in bootstrap number as a hyperparameter? Thanks! @cristinae @albarron

**Comment by cristinae** [comment]
Hi! Please have a look at this gist
https://gist.github.com/cristinae/1f7f0f4d4977e53b3fcc9df9d39b8f7f
This is still in the todo list

**Comment by cristinae** [comment]
Updated version uploaded
